// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class ObjectiveCFileOptions;
@class ObjectiveCFileOptionsBuilder;
@class PBDescriptorProto;
@class PBDescriptorProtoBuilder;
@class PBDescriptorProtoExtensionRange;
@class PBDescriptorProtoExtensionRangeBuilder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProtoBuilder;
@class PBEnumOptions;
@class PBEnumOptionsBuilder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProtoBuilder;
@class PBEnumValueOptions;
@class PBEnumValueOptionsBuilder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProtoBuilder;
@class PBFieldOptions;
@class PBFieldOptionsBuilder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProtoBuilder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSetBuilder;
@class PBFileOptions;
@class PBFileOptionsBuilder;
@class PBMessageOptions;
@class PBMessageOptionsBuilder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProtoBuilder;
@class PBMethodOptions;
@class PBMethodOptionsBuilder;
@class PBOneofDescriptorProto;
@class PBOneofDescriptorProtoBuilder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProtoBuilder;
@class PBServiceOptions;
@class PBServiceOptionsBuilder;
@class PBSourceCodeInfo;
@class PBSourceCodeInfoBuilder;
@class PBSourceCodeInfoLocation;
@class PBSourceCodeInfoLocationBuilder;
@class PBUninterpretedOption;
@class PBUninterpretedOptionBuilder;
@class PBUninterpretedOptionNamePart;
@class PBUninterpretedOptionNamePartBuilder;
@class VLTPBCapture;
@class VLTPBCaptureBuilder;
@class VLTPBDetectMotionRequest;
@class VLTPBDetectMotionRequestBuilder;
@class VLTPBSample;
@class VLTPBSampleBuilder;
@class VLTPBSensor;
@class VLTPBSensorBuilder;


typedef NS_ENUM(SInt32, VLTPBPlatformType) {
  VLTPBPlatformTypeIos = 0,
  VLTPBPlatformTypeAndroid = 1,
};

BOOL VLTPBPlatformTypeIsValidValue(VLTPBPlatformType value);
NSString *NSStringFromVLTPBPlatformType(VLTPBPlatformType value);

typedef NS_ENUM(SInt32, VLTPBSensorType) {
  VLTPBSensorTypeAccel = 0,
  VLTPBSensorTypeGyro = 1,
  VLTPBSensorTypeMag = 2,
  VLTPBSensorTypeGps = 3,
};

BOOL VLTPBSensorTypeIsValidValue(VLTPBSensorType value);
NSString *NSStringFromVLTPBSensorType(VLTPBSensorType value);


@interface VLTPBVelocityRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Capture_impressionId @"impressionId"
#define Capture_ifa @"ifa"
#define Capture_sequenceIndex @"sequenceIndex"
#define Capture_appId @"appId"
#define Capture_metadata @"metadata"
#define Capture_platform @"platform"
#define Capture_sensors @"sensors"
#define Capture_timestamp @"timestamp"
@interface VLTPBCapture : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTimestamp_:1;
  BOOL hasImpressionId_:1;
  BOOL hasIfa_:1;
  BOOL hasAppId_:1;
  BOOL hasMetadata_:1;
  BOOL hasSequenceIndex_:1;
  BOOL hasPlatform_:1;
  Float64 timestamp;
  NSString* impressionId;
  NSString* ifa;
  NSString* appId;
  NSString* metadata;
  UInt32 sequenceIndex;
  VLTPBPlatformType platform;
  NSMutableArray * sensorsArray;
}
- (BOOL) hasImpressionId;
- (BOOL) hasIfa;
- (BOOL) hasSequenceIndex;
- (BOOL) hasAppId;
- (BOOL) hasMetadata;
- (BOOL) hasPlatform;
- (BOOL) hasTimestamp;
@property (readonly, strong) NSString* impressionId;
@property (readonly, strong) NSString* ifa;
@property (readonly) UInt32 sequenceIndex;
@property (readonly, strong) NSString* appId;
@property (readonly, strong) NSString* metadata;
@property (readonly) VLTPBPlatformType platform;
@property (readonly, strong) NSArray * sensors;
@property (readonly) Float64 timestamp;
- (VLTPBSensor*)sensorsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (VLTPBCaptureBuilder*) builder;
+ (VLTPBCaptureBuilder*) builder;
+ (VLTPBCaptureBuilder*) builderWithPrototype:(VLTPBCapture*) prototype;
- (VLTPBCaptureBuilder*) toBuilder;

+ (VLTPBCapture*) parseFromData:(NSData*) data;
+ (VLTPBCapture*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VLTPBCapture*) parseFromInputStream:(NSInputStream*) input;
+ (VLTPBCapture*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VLTPBCapture*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (VLTPBCapture*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface VLTPBCaptureBuilder : PBGeneratedMessageBuilder {
@private
  VLTPBCapture* resultCapture;
}

- (VLTPBCapture*) defaultInstance;

- (VLTPBCaptureBuilder*) clear;
- (VLTPBCaptureBuilder*) clone;

- (VLTPBCapture*) build;
- (VLTPBCapture*) buildPartial;

- (VLTPBCaptureBuilder*) mergeFrom:(VLTPBCapture*) other;
- (VLTPBCaptureBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (VLTPBCaptureBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasImpressionId;
- (NSString*) impressionId;
- (VLTPBCaptureBuilder*) setImpressionId:(NSString*) value;
- (VLTPBCaptureBuilder*) clearImpressionId;

- (BOOL) hasIfa;
- (NSString*) ifa;
- (VLTPBCaptureBuilder*) setIfa:(NSString*) value;
- (VLTPBCaptureBuilder*) clearIfa;

- (BOOL) hasSequenceIndex;
- (UInt32) sequenceIndex;
- (VLTPBCaptureBuilder*) setSequenceIndex:(UInt32) value;
- (VLTPBCaptureBuilder*) clearSequenceIndex;

- (BOOL) hasAppId;
- (NSString*) appId;
- (VLTPBCaptureBuilder*) setAppId:(NSString*) value;
- (VLTPBCaptureBuilder*) clearAppId;

- (BOOL) hasMetadata;
- (NSString*) metadata;
- (VLTPBCaptureBuilder*) setMetadata:(NSString*) value;
- (VLTPBCaptureBuilder*) clearMetadata;

- (BOOL) hasPlatform;
- (VLTPBPlatformType) platform;
- (VLTPBCaptureBuilder*) setPlatform:(VLTPBPlatformType) value;
- (VLTPBCaptureBuilder*) clearPlatform;

- (NSMutableArray *)sensors;
- (VLTPBSensor*)sensorsAtIndex:(NSUInteger)index;
- (VLTPBCaptureBuilder *)addSensors:(VLTPBSensor*)value;
- (VLTPBCaptureBuilder *)setSensorsArray:(NSArray *)array;
- (VLTPBCaptureBuilder *)clearSensors;

- (BOOL) hasTimestamp;
- (Float64) timestamp;
- (VLTPBCaptureBuilder*) setTimestamp:(Float64) value;
- (VLTPBCaptureBuilder*) clearTimestamp;
@end

#define Sensor_type @"type"
#define Sensor_samples @"samples"
@interface VLTPBSensor : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasType_:1;
  VLTPBSensorType type;
  NSMutableArray * samplesArray;
}
- (BOOL) hasType;
@property (readonly) VLTPBSensorType type;
@property (readonly, strong) NSArray * samples;
- (VLTPBSample*)samplesAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (VLTPBSensorBuilder*) builder;
+ (VLTPBSensorBuilder*) builder;
+ (VLTPBSensorBuilder*) builderWithPrototype:(VLTPBSensor*) prototype;
- (VLTPBSensorBuilder*) toBuilder;

+ (VLTPBSensor*) parseFromData:(NSData*) data;
+ (VLTPBSensor*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VLTPBSensor*) parseFromInputStream:(NSInputStream*) input;
+ (VLTPBSensor*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VLTPBSensor*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (VLTPBSensor*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface VLTPBSensorBuilder : PBGeneratedMessageBuilder {
@private
  VLTPBSensor* resultSensor;
}

- (VLTPBSensor*) defaultInstance;

- (VLTPBSensorBuilder*) clear;
- (VLTPBSensorBuilder*) clone;

- (VLTPBSensor*) build;
- (VLTPBSensor*) buildPartial;

- (VLTPBSensorBuilder*) mergeFrom:(VLTPBSensor*) other;
- (VLTPBSensorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (VLTPBSensorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (VLTPBSensorType) type;
- (VLTPBSensorBuilder*) setType:(VLTPBSensorType) value;
- (VLTPBSensorBuilder*) clearType;

- (NSMutableArray *)samples;
- (VLTPBSample*)samplesAtIndex:(NSUInteger)index;
- (VLTPBSensorBuilder *)addSamples:(VLTPBSample*)value;
- (VLTPBSensorBuilder *)setSamplesArray:(NSArray *)array;
- (VLTPBSensorBuilder *)clearSamples;
@end

#define Sample_timestamp @"timestamp"
#define Sample_values @"values"
@interface VLTPBSample : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTimestamp_:1;
  Float64 timestamp;
  PBAppendableArray * valuesArray;
}
- (BOOL) hasTimestamp;
@property (readonly) Float64 timestamp;
@property (readonly, strong) PBArray * values;
- (Float32)valuesAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (VLTPBSampleBuilder*) builder;
+ (VLTPBSampleBuilder*) builder;
+ (VLTPBSampleBuilder*) builderWithPrototype:(VLTPBSample*) prototype;
- (VLTPBSampleBuilder*) toBuilder;

+ (VLTPBSample*) parseFromData:(NSData*) data;
+ (VLTPBSample*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VLTPBSample*) parseFromInputStream:(NSInputStream*) input;
+ (VLTPBSample*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VLTPBSample*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (VLTPBSample*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface VLTPBSampleBuilder : PBGeneratedMessageBuilder {
@private
  VLTPBSample* resultSample;
}

- (VLTPBSample*) defaultInstance;

- (VLTPBSampleBuilder*) clear;
- (VLTPBSampleBuilder*) clone;

- (VLTPBSample*) build;
- (VLTPBSample*) buildPartial;

- (VLTPBSampleBuilder*) mergeFrom:(VLTPBSample*) other;
- (VLTPBSampleBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (VLTPBSampleBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTimestamp;
- (Float64) timestamp;
- (VLTPBSampleBuilder*) setTimestamp:(Float64) value;
- (VLTPBSampleBuilder*) clearTimestamp;

- (PBAppendableArray *)values;
- (Float32)valuesAtIndex:(NSUInteger)index;
- (VLTPBSampleBuilder *)addValues:(Float32)value;
- (VLTPBSampleBuilder *)setValuesArray:(NSArray *)array;
- (VLTPBSampleBuilder *)setValuesValues:(const Float32 *)values count:(NSUInteger)count;
- (VLTPBSampleBuilder *)clearValues;
@end

#define DetectMotionRequest_id @"id"
#define DetectMotionRequest_userId @"userId"
#define DetectMotionRequest_sequenceIndex @"sequenceIndex"
#define DetectMotionRequest_platform @"platform"
#define DetectMotionRequest_timestamp @"timestamp"
#define DetectMotionRequest_modelName @"modelName"
#define DetectMotionRequest_sensors @"sensors"
@interface VLTPBDetectMotionRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTimestamp_:1;
  BOOL hasId_:1;
  BOOL hasUserId_:1;
  BOOL hasSequenceIndex_:1;
  BOOL hasPlatform_:1;
  Float64 timestamp;
  NSString* id;
  NSString* userId;
  UInt32 sequenceIndex;
  VLTPBPlatformType platform;
  NSMutableArray * modelNameArray;
  NSMutableArray * sensorsArray;
}
- (BOOL) hasId;
- (BOOL) hasUserId;
- (BOOL) hasSequenceIndex;
- (BOOL) hasPlatform;
- (BOOL) hasTimestamp;
@property (readonly, strong) NSString* id;
@property (readonly, strong) NSString* userId;
@property (readonly) UInt32 sequenceIndex;
@property (readonly) VLTPBPlatformType platform;
@property (readonly) Float64 timestamp;
@property (readonly, strong) NSArray * modelName;
@property (readonly, strong) NSArray * sensors;
- (NSString*)modelNameAtIndex:(NSUInteger)index;
- (VLTPBSensor*)sensorsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (VLTPBDetectMotionRequestBuilder*) builder;
+ (VLTPBDetectMotionRequestBuilder*) builder;
+ (VLTPBDetectMotionRequestBuilder*) builderWithPrototype:(VLTPBDetectMotionRequest*) prototype;
- (VLTPBDetectMotionRequestBuilder*) toBuilder;

+ (VLTPBDetectMotionRequest*) parseFromData:(NSData*) data;
+ (VLTPBDetectMotionRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VLTPBDetectMotionRequest*) parseFromInputStream:(NSInputStream*) input;
+ (VLTPBDetectMotionRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VLTPBDetectMotionRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (VLTPBDetectMotionRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface VLTPBDetectMotionRequestBuilder : PBGeneratedMessageBuilder {
@private
  VLTPBDetectMotionRequest* resultDetectMotionRequest;
}

- (VLTPBDetectMotionRequest*) defaultInstance;

- (VLTPBDetectMotionRequestBuilder*) clear;
- (VLTPBDetectMotionRequestBuilder*) clone;

- (VLTPBDetectMotionRequest*) build;
- (VLTPBDetectMotionRequest*) buildPartial;

- (VLTPBDetectMotionRequestBuilder*) mergeFrom:(VLTPBDetectMotionRequest*) other;
- (VLTPBDetectMotionRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (VLTPBDetectMotionRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (VLTPBDetectMotionRequestBuilder*) setId:(NSString*) value;
- (VLTPBDetectMotionRequestBuilder*) clearId;

- (BOOL) hasUserId;
- (NSString*) userId;
- (VLTPBDetectMotionRequestBuilder*) setUserId:(NSString*) value;
- (VLTPBDetectMotionRequestBuilder*) clearUserId;

- (BOOL) hasSequenceIndex;
- (UInt32) sequenceIndex;
- (VLTPBDetectMotionRequestBuilder*) setSequenceIndex:(UInt32) value;
- (VLTPBDetectMotionRequestBuilder*) clearSequenceIndex;

- (BOOL) hasPlatform;
- (VLTPBPlatformType) platform;
- (VLTPBDetectMotionRequestBuilder*) setPlatform:(VLTPBPlatformType) value;
- (VLTPBDetectMotionRequestBuilder*) clearPlatform;

- (BOOL) hasTimestamp;
- (Float64) timestamp;
- (VLTPBDetectMotionRequestBuilder*) setTimestamp:(Float64) value;
- (VLTPBDetectMotionRequestBuilder*) clearTimestamp;

- (NSMutableArray *)modelName;
- (NSString*)modelNameAtIndex:(NSUInteger)index;
- (VLTPBDetectMotionRequestBuilder *)addModelName:(NSString*)value;
- (VLTPBDetectMotionRequestBuilder *)setModelNameArray:(NSArray *)array;
- (VLTPBDetectMotionRequestBuilder *)clearModelName;

- (NSMutableArray *)sensors;
- (VLTPBSensor*)sensorsAtIndex:(NSUInteger)index;
- (VLTPBDetectMotionRequestBuilder *)addSensors:(VLTPBSensor*)value;
- (VLTPBDetectMotionRequestBuilder *)setSensorsArray:(NSArray *)array;
- (VLTPBDetectMotionRequestBuilder *)clearSensors;
@end


// @@protoc_insertion_point(global_scope)
