// Code generated by protoc-gen-go.
// source: velocity.proto
// DO NOT EDIT!

/*
Package VelocityProto is a generated protocol buffer package.

It is generated from these files:
	velocity.proto

It has these top-level messages:
	Capture
	Sensor
	Sample
	DetectMotionRequest
*/
package VelocityProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlatformType int32

const (
	PlatformType_IOS     PlatformType = 0
	PlatformType_Android PlatformType = 1
)

var PlatformType_name = map[int32]string{
	0: "IOS",
	1: "Android",
}
var PlatformType_value = map[string]int32{
	"IOS":     0,
	"Android": 1,
}

func (x PlatformType) Enum() *PlatformType {
	p := new(PlatformType)
	*p = x
	return p
}
func (x PlatformType) String() string {
	return proto.EnumName(PlatformType_name, int32(x))
}
func (x *PlatformType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PlatformType_value, data, "PlatformType")
	if err != nil {
		return err
	}
	*x = PlatformType(value)
	return nil
}
func (PlatformType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Sensor_Type int32

const (
	Sensor_Accel Sensor_Type = 0
	Sensor_Gyro  Sensor_Type = 1
	Sensor_Mag   Sensor_Type = 2
	Sensor_GPS   Sensor_Type = 3
)

var Sensor_Type_name = map[int32]string{
	0: "Accel",
	1: "Gyro",
	2: "Mag",
	3: "GPS",
}
var Sensor_Type_value = map[string]int32{
	"Accel": 0,
	"Gyro":  1,
	"Mag":   2,
	"GPS":   3,
}

func (x Sensor_Type) Enum() *Sensor_Type {
	p := new(Sensor_Type)
	*p = x
	return p
}
func (x Sensor_Type) String() string {
	return proto.EnumName(Sensor_Type_name, int32(x))
}
func (x *Sensor_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Sensor_Type_value, data, "Sensor_Type")
	if err != nil {
		return err
	}
	*x = Sensor_Type(value)
	return nil
}
func (Sensor_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Capture struct {
	ImpressionId     *string       `protobuf:"bytes,1,opt,name=impressionId" json:"impressionId,omitempty"`
	Ifa              *string       `protobuf:"bytes,2,req,name=ifa" json:"ifa,omitempty"`
	SequenceIndex    *uint32       `protobuf:"varint,3,req,name=sequenceIndex" json:"sequenceIndex,omitempty"`
	AppId            *string       `protobuf:"bytes,4,opt,name=appId" json:"appId,omitempty"`
	Metadata         *string       `protobuf:"bytes,5,opt,name=metadata" json:"metadata,omitempty"`
	Platform         *PlatformType `protobuf:"varint,6,req,name=platform,enum=VelocityProto.PlatformType" json:"platform,omitempty"`
	Sensors          []*Sensor     `protobuf:"bytes,7,rep,name=sensors" json:"sensors,omitempty"`
	Timestamp        *float64      `protobuf:"fixed64,8,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Capture) Reset()                    { *m = Capture{} }
func (m *Capture) String() string            { return proto.CompactTextString(m) }
func (*Capture) ProtoMessage()               {}
func (*Capture) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Capture) GetImpressionId() string {
	if m != nil && m.ImpressionId != nil {
		return *m.ImpressionId
	}
	return ""
}

func (m *Capture) GetIfa() string {
	if m != nil && m.Ifa != nil {
		return *m.Ifa
	}
	return ""
}

func (m *Capture) GetSequenceIndex() uint32 {
	if m != nil && m.SequenceIndex != nil {
		return *m.SequenceIndex
	}
	return 0
}

func (m *Capture) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *Capture) GetMetadata() string {
	if m != nil && m.Metadata != nil {
		return *m.Metadata
	}
	return ""
}

func (m *Capture) GetPlatform() PlatformType {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return PlatformType_IOS
}

func (m *Capture) GetSensors() []*Sensor {
	if m != nil {
		return m.Sensors
	}
	return nil
}

func (m *Capture) GetTimestamp() float64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type Sensor struct {
	Type             *Sensor_Type `protobuf:"varint,1,req,name=type,enum=VelocityProto.Sensor_Type" json:"type,omitempty"`
	Samples          []*Sample    `protobuf:"bytes,2,rep,name=samples" json:"samples,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Sensor) Reset()                    { *m = Sensor{} }
func (m *Sensor) String() string            { return proto.CompactTextString(m) }
func (*Sensor) ProtoMessage()               {}
func (*Sensor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Sensor) GetType() Sensor_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Sensor_Accel
}

func (m *Sensor) GetSamples() []*Sample {
	if m != nil {
		return m.Samples
	}
	return nil
}

type Sample struct {
	Timestamp        *float64  `protobuf:"fixed64,1,req,name=timestamp" json:"timestamp,omitempty"`
	Values           []float32 `protobuf:"fixed32,2,rep,name=values" json:"values,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Sample) Reset()                    { *m = Sample{} }
func (m *Sample) String() string            { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()               {}
func (*Sample) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Sample) GetTimestamp() float64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Sample) GetValues() []float32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type DetectMotionRequest struct {
	Id               *string       `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	UserId           *string       `protobuf:"bytes,2,req,name=userId" json:"userId,omitempty"`
	SequenceIndex    *uint32       `protobuf:"varint,3,req,name=sequenceIndex" json:"sequenceIndex,omitempty"`
	Platform         *PlatformType `protobuf:"varint,4,req,name=platform,enum=VelocityProto.PlatformType" json:"platform,omitempty"`
	Timestamp        *float64      `protobuf:"fixed64,5,req,name=timestamp" json:"timestamp,omitempty"`
	ModelName        []string      `protobuf:"bytes,6,rep,name=modelName" json:"modelName,omitempty"`
	Sensors          []*Sensor     `protobuf:"bytes,7,rep,name=sensors" json:"sensors,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *DetectMotionRequest) Reset()                    { *m = DetectMotionRequest{} }
func (m *DetectMotionRequest) String() string            { return proto.CompactTextString(m) }
func (*DetectMotionRequest) ProtoMessage()               {}
func (*DetectMotionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DetectMotionRequest) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *DetectMotionRequest) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *DetectMotionRequest) GetSequenceIndex() uint32 {
	if m != nil && m.SequenceIndex != nil {
		return *m.SequenceIndex
	}
	return 0
}

func (m *DetectMotionRequest) GetPlatform() PlatformType {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return PlatformType_IOS
}

func (m *DetectMotionRequest) GetTimestamp() float64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *DetectMotionRequest) GetModelName() []string {
	if m != nil {
		return m.ModelName
	}
	return nil
}

func (m *DetectMotionRequest) GetSensors() []*Sensor {
	if m != nil {
		return m.Sensors
	}
	return nil
}

func init() {
	proto.RegisterType((*Capture)(nil), "VelocityProto.Capture")
	proto.RegisterType((*Sensor)(nil), "VelocityProto.Sensor")
	proto.RegisterType((*Sample)(nil), "VelocityProto.Sample")
	proto.RegisterType((*DetectMotionRequest)(nil), "VelocityProto.DetectMotionRequest")
	proto.RegisterEnum("VelocityProto.PlatformType", PlatformType_name, PlatformType_value)
	proto.RegisterEnum("VelocityProto.Sensor_Type", Sensor_Type_name, Sensor_Type_value)
}

func init() { proto.RegisterFile("velocity.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0xd1, 0x8a, 0x13, 0x31,
	0x14, 0x86, 0x37, 0x99, 0xe9, 0x4c, 0xe7, 0x74, 0x5b, 0x66, 0xa3, 0x0b, 0x41, 0x6f, 0x86, 0x41,
	0x24, 0x28, 0xdb, 0x8b, 0x7d, 0x83, 0x45, 0x61, 0x99, 0x8b, 0xd5, 0x62, 0xc5, 0xfb, 0x30, 0x39,
	0x2b, 0x81, 0xc9, 0x24, 0x26, 0xe9, 0x62, 0x1f, 0xc1, 0x07, 0xf3, 0xd6, 0x67, 0x92, 0x89, 0x45,
	0xac, 0x14, 0xdd, 0xbb, 0x9c, 0xfc, 0xe7, 0x3f, 0xff, 0xc7, 0x39, 0xb0, 0x7a, 0xc0, 0xc1, 0xf6,
	0x3a, 0xee, 0xd7, 0xce, 0xdb, 0x68, 0xd9, 0xf2, 0xd3, 0xa1, 0xde, 0x4c, 0x65, 0xfb, 0x83, 0x40,
	0xf9, 0x46, 0xba, 0xb8, 0xf3, 0xc8, 0x9e, 0xc2, 0xb9, 0x36, 0xce, 0x63, 0x08, 0xda, 0x8e, 0x9d,
	0xe2, 0xa4, 0x21, 0xa2, 0x62, 0x0b, 0xc8, 0xf4, 0xbd, 0xe4, 0xb4, 0xa1, 0xa2, 0x62, 0x97, 0xb0,
	0x0c, 0xf8, 0x65, 0x87, 0x63, 0x8f, 0xdd, 0xa8, 0xf0, 0x2b, 0xcf, 0x1a, 0x2a, 0x96, 0x6c, 0x09,
	0x33, 0xe9, 0x5c, 0xa7, 0x78, 0x9e, 0x2c, 0x35, 0xcc, 0x0d, 0x46, 0xa9, 0x64, 0x94, 0x7c, 0x96,
	0x7e, 0xae, 0x60, 0xee, 0x06, 0x19, 0xef, 0xad, 0x37, 0xbc, 0x68, 0xa8, 0x58, 0x5d, 0x3f, 0x5f,
	0x1f, 0x81, 0xac, 0x37, 0x07, 0xf9, 0xe3, 0xde, 0x21, 0x7b, 0x09, 0x65, 0xc0, 0x31, 0x58, 0x1f,
	0x78, 0xd9, 0x64, 0x62, 0x71, 0x7d, 0xf9, 0x57, 0xf7, 0x36, 0xa9, 0xec, 0x02, 0xaa, 0xa8, 0x0d,
	0x86, 0x28, 0x8d, 0xe3, 0xf3, 0x86, 0x0a, 0xd2, 0x7e, 0x23, 0x50, 0x1c, 0x54, 0x01, 0x79, 0xdc,
	0x3b, 0xe4, 0x24, 0x05, 0x3e, 0x3b, 0x39, 0x62, 0xfd, 0x3b, 0x4f, 0x1a, 0x37, 0x60, 0xe0, 0xf4,
	0x74, 0x5e, 0x52, 0xdb, 0x2b, 0xc8, 0x53, 0x7f, 0x05, 0xb3, 0x9b, 0xbe, 0xc7, 0xa1, 0x3e, 0x63,
	0x73, 0xc8, 0x6f, 0xf7, 0xde, 0xd6, 0x84, 0x95, 0x90, 0xdd, 0xc9, 0xcf, 0x35, 0x9d, 0x1e, 0xb7,
	0x9b, 0x6d, 0x9d, 0xb5, 0xaf, 0xa1, 0xf8, 0x65, 0x3c, 0x06, 0x9d, 0x78, 0x08, 0x5b, 0x41, 0xf1,
	0x20, 0x87, 0xdd, 0x21, 0x92, 0xb6, 0xdf, 0x09, 0x3c, 0x79, 0x8b, 0x11, 0xfb, 0x78, 0x67, 0xa3,
	0xb6, 0xe3, 0x87, 0x69, 0xcf, 0x21, 0x32, 0x00, 0xaa, 0x55, 0xf2, 0x54, 0x93, 0x67, 0x17, 0xd0,
	0x77, 0xea, 0xdf, 0xe7, 0xf8, 0x73, 0xdb, 0xf9, 0xff, 0xb7, 0x7d, 0x04, 0x37, 0x4b, 0x70, 0x17,
	0x50, 0x19, 0xab, 0x70, 0x78, 0x27, 0x0d, 0xf2, 0xa2, 0xc9, 0x44, 0xf5, 0xd8, 0x9b, 0xbc, 0x7a,
	0x01, 0xe7, 0x47, 0xd3, 0x4b, 0xc8, 0xba, 0xf7, 0xdb, 0xfa, 0x8c, 0x2d, 0xa0, 0xbc, 0x19, 0x95,
	0xb7, 0x5a, 0xd5, 0xe4, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0xc4, 0xf2, 0xe0, 0x97, 0x02,
	0x00, 0x00,
}
